### PR TITLE
Add schema validation test

### PR DESCRIPTION
**Pull request by vitorespindola**
Add JSON Schema validation to CI to guarantee that only valid schema files are merged to repository.

@leop-tcto FINOS has a travis CI account available to configure this repository?

### CODE REVIEW

**Comment by leop-tcto** [comment]
@vitorespindola I don't know if FINOS has this. I would suggest we have this discussion on the mailing list.
You should send an email to help@finos.org and CC: voice@finos.org.

Do you want me to approve this PR in the meantime?

**Comment by vitorespindola** [comment]
@leop-tcto just sent the email. We should wait to see if we will have this available before merging it.

**Comment by vitorespindola** [comment]
@leop-tcto You can merge it now.

**Comment by leop-tcto** [comment]
OK @vitorespindola I am merging now.

**Pull request merged**
